# This workflow will build and push a node.js application to an Azure Web App when a commit is pushed to your default branch.
#El código presente en el archivo parece ser un fragmento de un objeto JSON mal formado que contiene información relacionada con una cartera de criptomonedas. Incluye detalles sobre transacciones, balances, contratos de tokens y configuraciones de red.

1. **Información de la Cartera**: Hay una sección que indica si la cartera está en línea y contiene direcciones de blockchain y hashes de transacciones.
   
2. **Transacciones**: Se listan varias transacciones internas, especificando el momento, los montos en ETH, las comisiones y los estados de las transacciones.

3. **Detalles del Token**: Se menciona información sobre un token específico (VERSE), incluyendo su contrato, valor actual, y la cantidad poseída en la cartera.

4. **Configuraciones de Gas**: Hay advertencias sobre el límite de gas y precios asociados a transacciones en Ethereum.

5. **Errores y Estado**: Muestra indicadores sobre errores posibles, estado de la red y el tipo de moneda preferida.

6. **Detalles del Usuario**: Incluye información sensible como nombre de usuario y un correo electrónico que no debería estar expuesto públicamente.

El código tiene varias secciones desestructuradas, errores de sintaxis y formatos inconsistente que lo hacen inválido como JSON.fe80::ec18:3bff:fe92:5164%dummy0
fe80::200:ff:fe00:0%rmnet1
2605:8d80:6e2:c5:9550:11ee:3eb6:b0c7
fe80::200:ff:fe00:0%rmnet2
2605:8d80:399:5b9c:777a:af4d:33d4:c11c
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
